"""
Pytest configuration and fixtures for OpenSNP Project 10 tests.
"""

import pytest
import pandas as pd
from pathlib import Path


@pytest.fixture
def sample_23andme_data():
    """Sample 23andMe format genotype data."""
    return [
        ["rs3094315", "1", "742429", "AG"],
        ["rs12124819", "1", "766409", "AA"],
        ["rs28765502", "1", "832918", "CC"],
        ["rs7537756", "1", "844113", "AG"],
        ["rs28444699", "1", "846808", "AA"],
    ]


@pytest.fixture
def sample_ancestry_data():
    """Sample AncestryDNA format genotype data."""
    return [
        ["rs3094315", "1", "742429", "A", "G"],
        ["rs12124819", "1", "766409", "A", "A"],
        ["rs28765502", "1", "832918", "C", "C"],
        ["rs7537756", "1", "844113", "A", "G"],
        ["rs28444699", "1", "846808", "A", "A"],
    ]


@pytest.fixture
def sample_ancestry_mapping():
    """Sample ancestry mapping DataFrame."""
    return pd.DataFrame({
        "raw_ancestry": [
            "British",
            "German",
            "East Asian",
            "Ashkenazi Jewish",
            "British + German",
        ],
        "tier0": ["EUR", "EUR", "Non-EUR", "Founder", "EUR"],
        "tier1": ["EUR_NW", "EUR_C", "EAS", "Ashkenazi", "EUR_NW"],
    })


@pytest.fixture
def sample_ibs_data():
    """Sample PLINK .genome format data."""
    return pd.DataFrame({
        "FID1": ["1", "1", "2"],
        "IID1": ["1", "1", "2"],
        "FID2": ["2", "3", "3"],
        "IID2": ["2", "3", "3"],
        "IBS0": [1000, 2000, 1500],
        "IBS1": [10000, 15000, 12000],
        "IBS2": [40000, 30000, 35000],
        "PI_HAT": [0.45, 0.15, 0.30],
        "DST": [0.65, 0.55, 0.60],
    })


@pytest.fixture
def temp_genotype_file(tmp_path):
    """Create a temporary 23andMe format file."""
    content = """# This data file generated by 23andMe at: Sat Jan 01 12:00:00 2026
# Below is a text version of your data.
# This file has the following format:
# rsid  chromosome  position  genotype
#
# build 37
rsid	chromosome	position	genotype
rs3094315	1	742429	AG
rs12124819	1	766409	AA
rs28765502	1	832918	CC
rs7537756	1	844113	AG
rs28444699	1	846808	AA
"""
    file_path = tmp_path / "sample_genotype.txt"
    file_path.write_text(content)
    return file_path
